name: Direct Check Secrets

# This workflow runs on pull requests from contributors
# It has no access to secrets for security reasons
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if secret is not empty
        id: check-secret
        run: |
          if [ -z "${{ secrets.TEST_SECRET }}" ]; then
            echo "ERROR: TEST_SECRET is empty or not set!"
            exit 1
          else
            echo "SUCCESS: TEST_SECRET is properly configured"
          fi

      - name: "Create commit status"
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if previous steps failed
            const checkResult = '${{ steps.check-secret.outcome }}';
            const state = checkResult === 'success' ? 'success' : 'failure';
            const description = checkResult === 'success' 
              ? 'Direct secret check passed! Everything is OK.' 
              : 'Direct secret check failed! Please check repository secrets.';

            // Create commit status
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: state,
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{ github.run_id }}`,
              description: description,
              context: 'direct-secrets-check'
            });
