name: Direct Check Secrets

# This workflow runs on pull requests from contributors
# It has no access to secrets for security reasons
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check if secret is not empty
        run: |
          if [ -z "${{ secrets.TEST_SECRET }}" ]; then
            echo "ERROR: TEST_SECRET is empty or not set!"
            exit 1
          else
            echo "SUCCESS: TEST_SECRET is properly configured"
          fi
