name: Receive PR

# This workflow runs on pull requests from contributors
# It has no access to secrets for security reasons
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  receive:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          echo "PR number: ${{ github.event.number }}"
          
      - name: "Create initial comment"
        id: create-comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.number }},
              body: '🔄 Running tests in the background... Please wait while we check the repository configuration.'
            });
            
            // Store comment ID for later updates
            core.setOutput('comment-id', comment.data.id);

      - name: Upload PR info as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/