name: Receive PR

# This workflow runs on pull requests from contributors
# It has no access to secrets for security reasons
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  receive:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Create initial pending statuses"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prSha = context.payload.pull_request.head.sha;
            console.log(`Creating pending statuses for SHA: ${prSha}`);
            // Create pending statuses for all checks
            const statuses = [
              {
                context: 'secrets-check',
                description: 'Secret check is running...'
              },
              {
                context: 'secrets-investigation', 
                description: 'Secret investigation is running...'
              }
            ];

            for (const status of statuses) {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: prSha,
                state: 'pending',
                target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{ github.run_id }}`,
                description: status.description,
                context: status.context
              });
            }
